# Generated by Django 6.0 on 2025-12-17 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Inscrições Abertas'), ('sorteio', 'Sorteio Realizado'), ('andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='aberta', max_length=20)),
                ('valor_premiacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(related_name='salas_inscritas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=700)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='competicao.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cabeca_de_chave', models.BooleanField(default=False)),
                ('pontuacao_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('membros', models.ManyToManyField(related_name='meus_grupos', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='competicao.sala')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicao.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='competicao.grupo')),
            ],
            options={
                'unique_together': {('grupo', 'jurado')},
            },
        ),
    ]
