# Generated by Django 6.0 on 2025-12-20 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='cabeca_de_chave',
        ),
        migrations.AddField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liderando', to=settings.AUTH_USER_MODEL, verbose_name='Cabeça de Chave'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_projeto', models.URLField(max_length=1000)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='competicao.grupo')),
            ],
        ),
    ]
