# Generated by Django 6.0 on 2025-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0002_remove_grupo_cabeca_de_chave_grupo_lider_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='duracao_horas',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sala',
            name='inicio_atividades',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
