# Generated by Django 6.0 on 2025-12-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0003_sala_duracao_horas_sala_inicio_atividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='sala',
        ),
    ]
