# Generated by Django 6.0 on 2025-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0004_remove_tema_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='temas',
            field=models.ManyToManyField(blank=True, related_name='salas', to='competicao.tema'),
        ),
    ]
