# Generated by Django 6.0 on 2025-12-21 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0005_sala_temas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='salas_inscritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
