# Generated by Django 6.0 on 2025-12-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='eh_jurado',
            field=models.BooleanField(default=False, verbose_name='É Jurado?'),
        ),
    ]
